defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  71aef9fa-1e77-4cfa-bbd1-a48006412d66: # Website by Steadfast
    enabledByDefault: true
    hasUrls: true
    template: _entries/home.twig
    uriFormat: __home__
type: single
